# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2017-2020 CERN.
# Copyright (C) 2020 Northwestern University.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
    - env: REQUIREMENTS=devel EXTRAS=sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"

cache:
  - pip

services:
    - mysql
    - postgresql

# Note: dist/sudo/api is required for MySQL 5.6 which adds support for
# fractional seconds in datetime columns.
dist: trusty
sudo: required
addons:
  postgresql: "9.4"
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6


env:
  global:
    - ES7_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.0-linux-x86_64.tar.gz"
    - ES_HOST=127.0.0.1
    - SQLALCHEMY_MYSQL_URI="mysql+pymysql://travis@localhost:3306/invenio"
    - SQLALCHEMY_POSTGRESQL_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  matrix:
    - REQUIREMENTS=lowest EXTRAS=mysql SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_MYSQL_URI
    - REQUIREMENTS=lowest EXTRAS=postgresql SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_POSTGRESQL_URI
    - REQUIREMENTS=release EXTRAS=mysql SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_MYSQL_URI
    - REQUIREMENTS=release EXTRAS=postgresql SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_POSTGRESQL_URI DEPLOY=true
    - REQUIREMENTS=devel EXTRAS=postgresql SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_POSTGRESQL_URI
    - REQUIREMENTS=devel EXTRAS=sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"

python:
  - "3.6"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES7_DOWNLOAD_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch > /tmp/local-es.log &"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e records,indexer,elasticsearch7,${EXTRAS} --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e records,indexer,elasticsearch7,${EXTRAS} --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e records,indexer,elasticsearch7,${EXTRAS} --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio;' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[docs,tests]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "C5bA1MnMDfNefFhrY/ixd4K57xNN8Fx8uI8/AEip+f/BCNq3GZpRzwtqv4bIMUc3y6ILDHF9k2cLi2N3a0bEqsiH2A8ytUbusTnxbfG7ND5LSA3+FUiJYuSimXQ2fkR6+kh9Q/wtjsj5V4SDLlDC1n9X+0Y083xggHDAUtB3l1NkV0YVB4JKprfdhYLrYr6+H3zkd2mmSlGPO7l4QAhto13CO3t8QdNhPUwiqyH0n5Q7NYm+E2iyw9SdMlA/LTKrcr33LTtq6CzyEMsszOwRVs+y+XZMUYdiNSzmQ3/llzvlB33LwXaTrUbVPpz+UYmnlRWQL4sPqj5b4x+4EL124NKDTFGnwhQjW5h48D7750VEvP1MXxSZSiPg8tD4dFrFeBWbYPVWbp+FBqz6pK6VcmZBr5bYwZUmjVtbIrag79APXox5cSoRayhL4WBlUxDtM8YEoByDpgLCr8lgTWyzAskbv5x0VfzoM1plbmRr/3NvCRFFhxT5R5xzup8+hzvs7DcnWH8zb2sK16X5D6yF6PJ2W9fq5EdA7tpLT+NiLH1w8O+duEH4OP8n67sq4zVR8gD8UvNLvpT9Lt83l1zjukXJ/KpkLus8iFoj6rjEzBgrqGgN2yYtutt+7VT30GJU9oNSm+EAhWmKof4d5mA3v0ztV9GhflgEeyS9dPLVrcg="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
    repo: inveniosoftware/invenio-pidrelations
    condition: $DEPLOY = true
