# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2017 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
    - mysql
    - postgresql

# Note: dist/sudo/api is required for MySQL 5.6 which adds support for
# fractional seconds in datetime columns.
dist: trusty
sudo: required
addons:
  postgresql: "9.4"
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6


env:
  - REQUIREMENTS=lowest EXTRAS=mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
  - REQUIREMENTS=lowest EXTRAS=postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=lowest EXTRAS=sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release EXTRAS=mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
  - REQUIREMENTS=release EXTRAS=postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" DEPLOY=true
  - REQUIREMENTS=release EXTRAS=sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel EXTRAS=mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://travis@localhost:3306/invenio"
  - REQUIREMENTS=devel EXTRAS=postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=devel EXTRAS=sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e records,indexer,${EXTRAS} --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e records,indexer,${EXTRAS} --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e records,indexer,${EXTRAS} --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio;' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all,${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "H1OevAFRKjXhhj2NZO71aB5NtyLv3D048BVRJ9e9bHNL+umrMCV5blu2C3QpRo6hJX8tZRB0feNxboCjYxoa+p1frtNdvPNAjuIfIWInf38+ho/KQxePhE1PYtPIfBAOusSdzJts8fRQmqRqH246TtOvAtHtfFLG7r5xsbaJINNIYxoquhQ0EihJkWUyPnXm/NkgMhB48ppUXKqm3Bis7AXTFZ5Iz1+1N/RW8ueoM0teupoS++yRFhVXlN3mSUAxiRtgejB76sqfgPaJnCIB67Tzf7cLVAi+/FhQl6xdUmxHy2BIZoLB22kU69B1dJJMvMdMzxbDdrcSVpwrHj4b59M4bzFRMj0UwM4nO0+omKChb62lGKiX/L2Bk9pw/boxG9ZkrECHtT7p7H6s1pMBhMLYozbD652flfG06/gokXP5N4b0mjdPzH0B2AVC1ojZFmY8mpeZlRU+LLhANRUwobmqcvDD0Y49BtPtHD4I4XWHSppabMtJhI3SGQKfa3ZPFsKuWEGNDr1lNu9rDG1y1/F/t7uURKQVah5Me7+yjE+gAYR4gs/bjlVMyiE/oKmtNOY3+uOTTNZOC8jl0FHml68GD3SV/nVPmxeFS+yx0qP3bYzewMJtR6E0dY8mcK2J2jc4Z7Kr1AL7TbjVe8FWGVadBRj+CheWK8JvN5eFd1o="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    repo: inveniosoftware/invenio-pidrelations
    condition: $DEPLOY = true
